services:
  _defaults:
    autowire: true
    autoconfigure: true

  Almefy\Client:
    arguments:
      - '%env(ALMEFY_KEY)%'
      - '%env(ALMEFY_SECRET)%'
      - '%env(ALMEFY_API)%'

  Almefy\AuthenticationBundle\Service\AlmefySessionManager:
    public: true

  Almefy\AuthenticationBundle\Security\AlmefyUserIdentityProvider:
    public: true

  Almefy\AuthenticationBundle\Security\AlmefyAuthenticator:
    public: true
    arguments:
      $apiSecret: '%env(ALMEFY_SECRET)%'

  Almefy\AuthenticationBundle\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
